// GRUNT - GENERATED BUILD FILE - DO NOT EDIT MANUALLY, OK? // 
Amalia.Data = {
	about: '<p>I find I am happiest when I am making things. These things include, but are not at all limited to web apps, hackathon projects, physical computing contraptions (think: arduino, raspberry pi, and the Internet of Things), and music. I am fascinated with the way things work and have been a tinkerer for as long as I can remember&mdash;<a href="http://www.aamaliaa.com/post/56397901620/legos-were-are-my-favorite">LEGOs</a> were and still are my favorite toy. That cool place where technology, design, and creativity intersect is where I like to spend most of my time.</p><p>I am curious. I like to learn something new every day and am always trying to discover new ways to do just that.</p><p>I currently work as a <strong>web applications developer</strong> at <strong><a href="http://www.qz.com">Quartz</a></strong>.</p>',
	projects: {}
}; 

 Amalia.Data.projects.bathroom_vacancy_light = '<p>I used to live in a 3-bedroom apartment with only one bathroom and wanted an easy way to know when the bathroom was unoccupied without leaving my room (and my bed, for that matter). So, like any other normal person, I decided the solution was to design my own airplane-style lavatory vacancy light for my room.</p><p>I used an Arduino equipped with a magnetic reed switch and a WiFly attached to my bathroom doorframe that transmitted signals using Pusher via wifi. On the receiving end in my bedroom was a Raspberry Pi which was subscribed to the Arduino&#39;s Pusher channel. When signal was received upon door open and close, the Pi triggered an LED via its GPIO.</p><iframe src="http://player.vimeo.com/video/54831393" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';

 Amalia.Data.projects.citibike = '<p>When Citibike was announced, I think I was more excited about the data that would be generated and shared publicly than the bikes themselves. This project is a quick experiment and current work in progress that is built on top of the real-time Citibike stations data.</p><p>I used Google Maps and d3.js to plot out each of the stations on the map:</p><ul><li>green stations have &gt; 5 bikes available</li><li>orange stations have between 1 and 5 bikes available</li><li>red stations have 0 bikes available</li><li>a green station with a larger circle radius has more available bikes</li></ul><p>To use the tool, simply enter an origin address and a destination address (both NYC addresses), and hit the &quot;plot&quot; button. Bicycle directions between the closest stations to each of the two points that you&#39;ve specified will be plotted on the map.</p>';

 Amalia.Data.projects.fanfare = '<iframe width="640" height="360" src="http://www.youtube.com/embed/gMG8yLw0-q0?rel=0" frameborder="0" allowfullscreen></iframe><p>Fanfare allowed concertgoers to link up with Facebook friends with similar musical tastes and assisted with group ticket purchasing/distributing of funds.</p><p>As a huge music fan and concertgoer myself, I came up with the idea after trying and failing to find a friend to go see <a href="http://soundcloud.com/quadronmusic">Quadron</a> with me at Rockwood Music Hall.</p><p>The app was written in PHP and Javascript and utilized the Facebook and Songkick APIs in less than 24 hours for AngelHack NYC 2012. My team took home a prize from Facebook for Fanfare’s use of the Facebook Open Graph API.</p>';

 Amalia.Data.projects.fourplay = '<div style=\'text-align:center; padding:15px;\'>    <iframe src=\'http://www.snappytv.com/snap/fourplay-mashes-up-foursqaure-checkins-and-craigslist-miss-about-techcrunch-disrupt-ny-hackathon-2012-on-techcrunch-disrupt-ny-hackathon?w=500&h=312\' width=\'500\' height=\'312\' frameborder=\'0\' scrolling=\'no\' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div><p>Fourplay mashed up Craigslist Missed Connection listings and Foursquare User data to bring users missed connections that happened near or at their check-ins.</p><p>In order to achieve this we:</p><ul><li>screenscaped Craigslist Missed Connections with a <a href="https://scraperwiki.com/scrapers/ottawa_craigslist_missed_connections_1/">Python script</a></li><li>analyzed each post for GPS data using the <a href="http://apis.metalayer.com/">Metalayer Text API</a></li><li>then used the GPS information to locate and map locations using the <a href="http://developer.factual.com/display/docs/Factual+Developer+APIs+Version+3">Factual</a> and <a href="https://developer.foursquare.com/">Foursquare</a> APIs</li></ul><p>My team was awarded the Metalayer API Award for our use of the Metalayer Text API to analyze the missed connection data.</p><h3 id="press">Press</h3><ul><li><a href="http://blog.metalayer.com/post/23444677000/fourplay-and-sidewinder-win-metalayers-api-hackathon">Fourplay and Sidewinder Win MetaLayer’s API Hackathon</a></li></ul>';

 Amalia.Data.projects.ikea_timelapse = '<p>When I moved into my apartment in the summer of 2011, I made the usual trip to IKEA and then single-handedly built all of my furniture myself. Here is video proof:</p><h3 id="a-dresser-">A dresser.</h3><iframe src="http://player.vimeo.com/video/23299173" width="500" height="375" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe><h3 id="a-bed-">A bed.</h3><iframe src="http://player.vimeo.com/video/23340498" width="500" height="375" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>';

 Amalia.Data.projects.turnup_js = '<p>turnUp.js is a jQuery plugin that, given a list of strings, continuously grabs one string randomly and &quot;turns it up&quot;.</p><h1 class=\'turnup\' style=\'text-align: center;\'>NYMERIA</h1><p>I came across a similar implementation of this effect while browsing the Internet one day and decided that it might make a useful plugin for my portfolio (see the &#39;about&#39; page) and other future projects.</p><h3 id="how-to-use">How to Use</h3><p>It&#39;s super simple to plug it in your code:</p><pre><code>$(&#39;#title&#39;).turnup({ list: [&#39;one&#39;, &#39;two&#39;, &#39;three&#39;, &#39;four&#39;] });</code></pre><p>You can also change the CSS3 transition and interval time:</p><pre><code>$(&#39;#title&#39;).turnup({    list: [&#39;Grey Wind&#39;, &#39;Lady&#39;, &#39;Nymeria&#39;, &#39;Summer&#39;, &#39;Shaggy Dog&#39;],    transition: &#39;all 250ms ease&#39;,    interval: 450});</code></pre><h3 id="options">Options</h3><ul><li><code>list: [&#39;one&#39;, &#39;two&#39;, &#39;three&#39;, &#39;four&#39;]</code> - an array of strings</li><li><code>transition: &#39;all 250ms ease&#39;</code> - valid css string</li><li><code>interval: 450</code> - time between words (in milliseconds)</li></ul><h3 id="public-methods">Public Methods</h3><p>If you want to stop an instance after it has been instantiated, just tell it to stop.</p><pre><code>$(&#39;#title&#39;).turnup(&#39;stop&#39;);</code></pre><p>Then you can also turn up again!</p><pre><code>$(&#39;#title&#39;).turnup(&#39;start&#39;);</code></pre><h3 id="to-do">To Do</h3><ul><li>add options for cycling through list (i.e. linearly, alphabetically) instead of at random</li><li>CSS3 animation support for transitions (i.e. zoom/fade in from left, zoom/fade out upwards, etc)</li></ul>';

 Amalia.Data.projects.voteforjordan = '<iframe src="http://player.vimeo.com/video/50576416" width="500" height="281" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe><p>Jordan was a Florida resident who chose to let the world of Twitter decide which candidate would get his vote in the 2012 presidential election. Participants submitted their votes by hashtagging their tweets with either <a href="http://twitter.com/search?q=%23jordanvoteromney&amp;src=typd&amp;mode=realtime">#jordanvoteromney</a> or <a href="https://twitter.com/search?q=%23jordanvoteobama&amp;src=typd&amp;mode=realtime">#jordanvoteobama</a>. The candidate that received the most votes was chosen on Jordan’s absentee ballot.</p><p>I worked on this project with a team of art directors and copywriters and led the development of the voting system as well as the website myself. I set up a continuously running PHP script that utilized the Twitter Streaming API to filter the hashtag &quot;tweet-votes&quot; and update the percentages on the Vote For Jordan site in real-time.</p>';

